### ISSUE TITLE
TypeError: split() takes no keyword arguments

### ISSUE THREAD

**Issue by tph-thuering** [vecnet/openmalaria.tools#5]
I receive an error when trying to generate Documentation for schema-34. (related to https://github.com/SwissTPH/openmalaria/issues/89) 

``````
$ generateDoc.py build/schema/scenario_34.xsd
Generated schema 34 documentation
=================================
This page is automatically generated from the following schema file: `scenario_34.xsd`.
I recommend against editing it because edits will likely be lost later.

Key:
\```
    abc             required (one)
  [ def ]           optional (zero or one)
  ( ghi )*          any number (zero or more)
  ( jkl )+          at least one
  ( mno ){2,inf}    two or more occurrences
\```
Traceback (most recent call last):
  File "/usr/local/bin/generateDoc.py", line 579, in <module>
    main()
  File "/usr/local/bin/generateDoc.py", line 549, in main
    translate(f_in, sys.stdout, schema_name)
  File "/usr/local/bin/generateDoc.py", line 502, in translate
    omroot = Element(child)
  File "/usr/local/bin/generateDoc.py", line 390, in __init__
    Node.__init__(self, node)
  File "/usr/local/bin/generateDoc.py", line 174, in __init__
    self.read_child(child)
  File "/usr/local/bin/generateDoc.py", line 397, in read_child
    Node.read_child(self, child)
  File "/usr/local/bin/generateDoc.py", line 183, in read_child
    self.appinfo = parse_appinfo(appinfo.text)
  File "/usr/local/bin/generateDoc.py", line 124, in parse_appinfo
    parts = pair.split(':', maxsplit=1)
TypeError: split() takes no keyword arguments
``````

**Comment by tph-thuering** [comment]
The same error occurs when using scenario_33.xsd from https://github.com/SwissTPH/openmalaria/blob/develop/schema/scenario_33.xsd

**Comment by tph-thuering** [comment]
Maybe a python version issue?

```
$ ls -l `which python`
lrwxrwxrwx 1 root root 9 Mär 17 14:00 /usr/bin/python -> python2.7
```
